apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeploy
  labels:
    app: appdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-project
  template:
    metadata:
      labels:
        app: app-project
    spec:
      containers:
        - name: scacloudproject
          image: cloudproject1.azurecr.io/onyiiee/demoapp1:release0.1
          ports:
            - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: cloudapp-test-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: app-project